//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InplayBet.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bet : BaseData
    {
        public int BetId { get; set; }
        public int BetNumber { get; set; }
        public int TeamAId { get; set; }
        public int TeamBId { get; set; }
        public int LegueId { get; set; }
        public int ChallengeId { get; set; }
        public string BetType { get; set; }
        public string Odds { get; set; }
        public decimal BetPlaced { get; set; }
        public decimal WiningTotal { get; set; }
        public decimal LoosingTotal { get; set; }
        public string BetStatus { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Legue Legue { get; set; }
    }
}
