//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InplayBet.Web.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report : BaseData
    {
        public int ReportId { get; set; }
        public int ReportedBy { get; set; }
        public int ReportedUserId { get; set; }
        public int ReportedChallengeId { get; set; }
        public string Comment { get; set; }
        public string ReportStatus { get; set; }
        public int StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual Status Status { get; set; }
        public virtual User UserTo { get; set; }
        public virtual User UserBy { get; set; }
    }
}
